### ISSUE TITLE
What version of Python does this tool use?

### ISSUE THREAD

**Issue by imjinjia** [LostTemplarRH/innocence-r#5]
I got a bunch of errors when i use python3.7.9 .

**Comment by LostTemplarRH** [comment]
I have 3.9 at the moment so that should work.

Am Mo., 28. März 2022 um 08:23 Uhr schrieb imjinjia <
***@***.***>:

**Comment by imjinjia** [comment]
@LostTemplarRH 
Thank you ,I'll try 3.9 later.
